version: '3.8'

services:
  backend:
    build:
      context: ./apps/my-nest-app
      dockerfile: Dockerfile
    container_name: my-nest-app-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/my-vue-app
      dockerfile: Dockerfile
    container_name: my-vue-app-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

  angular-app:
    build:
      context: ./apps/my-angular-app
      dockerfile: Dockerfile
    container_name: my-angular-app-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
