apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nest-app
  template:
    metadata:
      labels:
        app: my-nest-app
    spec:
      containers:
        - name: my-nest-app
          image: your-dockerhub-username/my-nest-app:latest
          ports:
            - containerPort: 3000
          env:
            # Optional: environment variables here
            # - name: NODE_ENV
            #   value: production
